HoiioHTTP={HoiioAPIURL:{supportedCountries:"https://secure.hoiio.com/open/number/get_countries",availableNumbers:"https://secure.hoiio.com/open/number/get_choices",getNumberRates:"https://secure.hoiio.com/open/number/get_rates",subscription:"https://secure.hoiio.com/open/number/subscribe",configForwarding:"https://secure.hoiio.com/open/number/update_forwarding",subscribedNumbers:"https://secure.hoiio.com/open/number/get_active",sendSMS:"https://secure.hoiio.com/open/sms/send",sendBulkSMS:"https://secure.hoiio.com/open/sms/bulk_send",
getSMSHistory:"https://secure.hoiio.com/open/sms/get_history",getSMSRate:"https://secure.hoiio.com/open/sms/get_rate",getSMSStatus:"https://secure.hoiio.com/open/sms/query_status",makeCall:"https://secure.hoiio.com/open/voice/call",makeConference:"https://secure.hoiio.com/open/voice/conference",hangupCall:"https://secure.hoiio.com/open/voice/hangup",getCallHistory:"https://secure.hoiio.com/open/voice/get_history",getCallRate:"https://secure.hoiio.com/open/voice/get_rate",getCallStatus:"https://secure.hoiio.com/open/voice/query_status",
getUserBalance:"https://secure.hoiio.com/open/user/get_balance",getUserInfo:"https://secure.hoiio.com/open/user/get_info",sendFax:"https://secure.hoiio.com/open/fax/send",getFaxHistory:"https://secure.hoiio.com/open/fax/get_history",getFaxRate:"https://secure.hoiio.com/open/fax/get_rate",getFaxStatus:"https://secure.hoiio.com/open/fax/query_status",dial:"https://secure.hoiio.com/open/ivr/start/dial",play:"https://secure.hoiio.com/open/ivr/middle/play",gather:"https://secure.hoiio.com/open/ivr/middle/gather",
record:"https://secure.hoiio.com/open/ivr/middle/record",monitor:"https://secure.hoiio.com/open/ivr/middle/monitor",transfer:"https://secure.hoiio.com/open/ivr/end/transfer",hangup:"https://secure.hoiio.com/open/ivr/end/hangup"},getAPIURL:function(a){return HoiioHTTP.HoiioAPIURL[a]},getXMLHTTPRequest:function(){return window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")},converJSonToQueryString:function(a){var b="";a=a||{};for(key in a)b+=key+"="+a[key]+"&";return b=b.slice(0,
b.length-1)},makeHttpRequest:function(a,b,c,d){var e=HoiioHTTP.getXMLHTTPRequest();(function(){e.onreadystatechange=function(){if(4==e.readyState&&200==e.status){var a=eval("("+e.response+")");d.call(a,a)}}})();c=c||"POST";b=HoiioHTTP.converJSonToQueryString(b);a=HoiioHTTP.getAPIURL(a);"GET"==c.toUpperCase()?HoiioHTTP.excuteGETRequest(e,b?a:a+"?"+b):HoiioHTTP.excutePOSTRequest(e,a,b)},excuteGETRequest:function(a,b){a.open("GET",b,!0);a.send(null)},excutePOSTRequest:function(a,b,c){a.open("POST",b,
!0);a.setRequestHeader("Content-type","application/json");a.send(c)}},HoiioNumber=function(a,b){HoiioNumber.app_id=a;HoiioNumber.access_token=b;HoiioNumber.hoiioHttp=HoiioHTTP};HoiioNumber.prototype.supportedCountries=function(a){HoiioNumber.hoiioHttp.makeHttpRequest("supportedCountries",{app_id:HoiioNumber.app_id,access_token:HoiioNumber.access_token},"POST",a)};
HoiioNumber.prototype.availableNumbers=function(a,b,c,d){a={app_id:HoiioNumber.app_id,access_token:HoiioNumber.access_token,country:a,state:b};d&&d.page&&(a.page=d.page);HoiioNumber.hoiioHttp.makeHttpRequest("availableNumbers",a,"POST",c)};HoiioNumber.prototype.rates=function(a,b){hoiio_http.makeHttpRequest("getNumberRates",{app_id:HoiioNumber.app_id,access_token:HoiioNumber.access_token,country:a},"POST",b)};
HoiioNumber.prototype.subscription=function(a,b,c){HoiioNumber.hoiioHttp.makeHttpRequest("subscription",{app_id:HoiioNumber.app_id,access_token:HoiioNumber.access_token,number:a,duration:b},"POST",c)};
HoiioNumber.prototype.configForwarding=function(a,b,c){a={app_id:HoiioNumber.app_id,access_token:HoiioNumber.access_token,number:a};if(void 0!=c){var d=c.forward_to,e=c.forward_sms_to;c=c.mode;void 0!=d&&(a.forward_to=d);void 0!=e&&(a.forward_sms_to=e);void 0!=c&&(a.mode=c)}HoiioNumber.hoiioHttp.makeHttpRequest("configForwarding",a,"POST",b)};
HoiioNumber.prototype.subscribedNumbers=function(a){HoiioNumber.hoiioHttp.makeHttpRequest("subscribedNumbers",{app_id:HoiioNumber.app_id,access_token:HoiioNumber.access_token},"POST",a)};HoiioSMS=function(a,b){HoiioSMS.app_id=a;HoiioSMS.access_token=b;HoiioSMS.hoiioHttp=HoiioHTTP};
HoiioSMS.prototype.send=function(a,b,c,d){a={app_id:HoiioSMS.app_id,access_token:HoiioSMS.access_token,dest:a,msg:b};if(void 0!=d){b=d.sender_name;var e=d.tag;d=d.notify_url;void 0!=b&&(a.sender_name=b);void 0!=e&&(a.tag=e);void 0!=d&&(a.notify_url=d)}HoiioSMS.hoiioHttp.makeHttpRequest("sendSMS",a,"POST",c)};
HoiioSMS.prototype.bulkSend=function(a,b,c,d){a={app_id:HoiioSMS.app_id,access_token:HoiioSMS.access_token,dest:a,msg:b};if(void 0!=d){b=d.sender_name;var e=d.tag;d=d.notify_url;void 0!=b&&(a.sender_name=b);void 0!=e&&(a.tag=e);void 0!=d&&(a.notify_url=d)}HoiioSMS.hoiioHttp.makeHttpRequest("sendBulkSMS",a,"POST",c)};
HoiioSMS.prototype.history=function(a,b){var c={app_id:HoiioSMS.app_id,access_token:HoiioSMS.access_token};if(void 0!=options){var d=options.from,e=options.to,f=options.page,g=options.page_size;void 0!=d&&(c.from=d);void 0!=e&&(c.to=e);void 0!=f&&(c.page=f);void 0!=g&&(c.page_size=g)}HoiioSMS.hoiioHttp.makeHttpRequest("getSMSHistory",c,"POST",a)};
HoiioSMS.prototype.rate=function(a,b,c,d){HoiioSMS.hoiioHttp.makeHttpRequest("getSMSRate",{app_id:HoiioSMS.app_id,access_token:HoiioSMS.access_token,dest:a,incoming:b,msg:c},"POST",d)};HoiioSMS.prototype.queryStatus=function(a,b){HoiioSMS.hoiioHttp.makeHttpRequest("getSMSStatus",{app_id:HoiioSMS.app_id,access_token:HoiioSMS.access_token,txn_ref:a},"POST",b)};var HoiioVoice=function(a,b){HoiioVoice.app_id=a;HoiioVoice.access_token=b;HoiioVoice.hoiioHttp=HoiioHTTP};
HoiioVoice.prototype.call=function(a,b,c){a={app_id:HoiioVoice.app_id,access_token:HoiioVoice.access_token,dest2:a};if(void 0!=c){var d=c.dest1,e=c.caller_id,f=c.max_duration,g=c.tag;c=c.notify_url;void 0!=d&&(a.dest1=d);void 0!=e&&(a.caller_id=e);void 0!=f&&(a.max_duration=f);void 0!=g&&(a.tag=g);void 0!=c&&(a.notify_url=c)}HoiioVoice.hoiioHttp.makeHttpRequest("makeCall",a,"POST",b)};
HoiioVoice.prototype.conference=function(a,b,c){a={app_id:HoiioVoice.app_id,access_token:HoiioVoice.access_token,dest:a};if(void 0!=options){b=options.room;c=options.caller_id;var d=options.tag,e=options.notify_url;void 0!=b&&(a.room=b);void 0!=c&&(a.caller_id=c);void 0!=d&&(a.tag=d);void 0!=e&&(a.notify_url=e)}HoiioVoice.hoiioHttp.makeHttpRequest("makeConference",a,"POST",callbackFunction)};
HoiioVoice.prototype.hangup=function(a,b){HoiioVoice.hoiioHttp.makeHttpRequest("hangupCall",{app_id:HoiioVoice.app_id,access_token:HoiioVoice.access_token,txn_ref:a},"POST",callbackFunction)};
HoiioVoice.prototype.history=function(a,b){var c={app_id:HoiioVoice.app_id,access_token:HoiioVoice.access_token};if(void 0!=b){var d=b.from,e=b.to,f=b.page,g=b.page_size;void 0!=d&&(c.from=d);void 0!=e&&(c.to=e);void 0!=f&&(c.page=f);void 0!=g&&(c.page_size=g)}HoiioVoice.hoiioHttp.makeHttpRequest("getCallHistory",c,"POST",a)};
HoiioVoice.prototype.rate=function(a,b,c){HoiioVoice.hoiioHttp.makeHttpRequest("getCallRate",{app_id:HoiioVoice.app_id,access_token:HoiioVoice.access_token,dest1:a,dest2:b},"POST",callback)};HoiioVoice.prototype.queryStatus=function(a,b){HoiioVoice.hoiioHttp.makeHttpRequest("getCallStatus",{app_id:HoiioVoice.app_id,access_token:HoiioVoice.access_token,txn_ref:a},"POST",callbackFunction)};var HoiioAccount=function(a,b){HoiioAccount.app_id=a;HoiioAccount.access_token=b;HoiioAccount.hoiioHttp=HoiioHTTP};
HoiioAccount.prototype.balance=function(a){HoiioAccount.hoiioHttp.makeHttpRequest("getUserBalance",{app_id:HoiioAccount.app_id,access_token:HoiioAccount.access_token},"POST",a)};HoiioAccount.prototype.info=function(a){hoiio_http.makeHttpRequest("getUserInfo",{app_id:HoiioAccount.app_id,access_token:HoiioAccount.access_token},"POST",a)};var HoiioFax=function(a,b){HoiioFax.app_id=a;HoiioFax.access_token=b;HoiioFax.hoiioHttp=HoiioHTTP};
HoiioFax.prototype.send=function(a,b,c,d){a={app_id:HoiioFax.app_id,access_token:HoiioFax.access_token,dest:a,file:b};if(void 0!=d){b=d.filename;var e=d.caller_id,f=d.tag;d=d.notify_url;void 0!=b&&(a.filename=b);void 0!=e&&(a.caller_id=e);void 0!=f&&(a.tag=f);void 0!=d&&(a.notify_url=d)}HoiioFax.hoiioHttp.makeHttpRequest("sendFax",a,"POST",c)};
HoiioFax.prototype.history=function(a,b){var c={app_id:HoiioFax.app_id,access_token:HoiioFax.access_token};if(void 0!=b){var d=b.from,e=b.to,f=b.page,g=b.page_size,h=b.type,k=b.src,l=b.dest,m=b.tag;void 0!=d&&(c.from=d);void 0!=e&&(c.to=e);void 0!=f&&(c.page=f);void 0!=g&&(c.page_size=g);void 0!=h&&(c.type=h);void 0!=k&&(c.src=k);void 0!=l&&(c.dest=l);void 0!=m&&(c.tag=m)}HoiioFax.hoiioHttp.makeHttpRequest("getFaxHistory",c,"POST",a)};
HoiioFax.prototype.rate=function(a,b,c){HoiioFax.hoiioHttp.makeHttpRequest("getFaxRate",{app_id:HoiioFax.app_id,access_token:HoiioFax.access_token,dest:a,incoming:b},"POST",c)};HoiioFax.prototype.queryStatus=function(a,b){HoiioFax.hoiioHttp.makeHttpRequest("getFaxStatus",{app_id:HoiioFax.app_id,access_token:HoiioFax.access_token,txn_ref:a},"POST",b)};var HoiioIVR=function(a,b){HoiioIVR.app_id=a;HoiioIVR.access_token=b;HoiioIVR.hoiioHttp=HoiioHTTP};
HoiioIVR.prototype.dial=function(a,b,c){a={app_id:HoiioIVR.app_id,access_token:HoiioIVR.access_token,dest:a};if(void 0!=c){var d=c.msg,e=c.caller_id,f=c.max_duration,g=c.tag;c=c.notify_url;void 0!=d&&(a.msg=d);void 0!=e&&(a.caller_id=e);void 0!=f&&(a.max_duration=f);void 0!=g&&(a.tag=g);void 0!=c&&(a.notify_url=c)}HoiioIVR.hoiioHttp.makeHttpRequest("dial",a,"POST",b)};
HoiioIVR.prototype.play=function(a,b,c){a={app_id:HoiioIVR.app_id,access_token:HoiioIVR.access_token,session:a};if(void 0!=c){var d=c.msg,e=c.tag;c=c.notify_url;void 0!=d&&(a.msg=d);void 0!=e&&(a.tag=e);void 0!=c&&(a.notify_url=c)}HoiioIVR.hoiioHttp.makeHttpRequest("play",a,"POST",b)};
HoiioIVR.prototype.gather=function(a,b,c,d){a={app_id:HoiioIVR.app_id,access_token:HoiioIVR.access_token,session:a,notify_url:b};if(void 0!=d){b=d.msg;var e=d.max_digits,f=d.timeout,g=d.attempts;d=d.tag;void 0!=b&&(a.msg=b);void 0!=e&&(a.max_digits=e);void 0!=f&&(a.timeout=f);void 0!=g&&(a.attempts=g);void 0!=d&&(a.tag=d)}HoiioIVR.hoiioHttp.makeHttpRequest("gather",a,"POST",c)};
HoiioIVR.prototype.record=function(a,b,c,d){a={app_id:HoiioIVR.app_id,access_token:HoiioIVR.access_token,session:a,notify_url:b};if(void 0!=d){b=d.msg;var e=d.max_duration;d=d.tag;void 0!=b&&(a.msg=b);void 0!=e&&(a.max_duration=e);void 0!=d&&(a.tag=d)}HoiioIVR.hoiioHttp.makeHttpRequest("record",a,"POST",c)};
HoiioIVR.prototype.monito=function(a,b,c,d){a={app_id:HoiioIVR.app_id,access_token:HoiioIVR.access_token,session:a,notify_url:b};void 0!=d&&(b=d.msg,d=d.tag,void 0!=b&&(a.msg=b),void 0!=d&&(a.tag=d));HoiioIVR.hoiioHttp.makeHttpRequest("monitor",a,"POST",c)};
HoiioIVR.prototype.transfer=function(a,b,c,d){a={app_id:HoiioIVR.app_id,access_token:HoiioIVR.access_token,session:a,dest:b};if(void 0!=d){b=d.msg;var e=d.caller_id,f=d.on_failure,g=d.tag;d=d.notify_url;void 0!=b&&(a.msg=b);void 0!=e&&(a.caller_id=e);void 0!=f&&(a.on_failure=f);void 0!=g&&(a.tag=g);void 0!=d&&(a.notify_url=d)}HoiioIVR.hoiioHttp.makeHttpRequest("transfer",a,"POST",c)};
HoiioIVR.prototype.hangup=function(a,b,c){a={app_id:HoiioIVR.app_id,access_token:HoiioIVR.access_token,session:a};if(void 0!=c){var d=c.msg,e=c.tag;c=c.notify_url;void 0!=d&&(a.msg=d);void 0!=e&&(a.tag=e);void 0!=c&&(a.notify_url=c)}HoiioIVR.hoiioHttp.makeHttpRequest("hangup",a,"POST",b)};